version: '3.8'

services:

  # ==================
  # Angular portal
  # ==================
  cp-prt:
    image: cp-prt
    build:
      context: ./CP_PRT
    container_name: cp-prt
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    networks:
      - cabinetpro

  # ==================
  # Gateway
  # ==================
  cp-gwt-1:
    build:
      context: CP_GWT
      dockerfile: Dockerfile
    container_name: cp-gwt-1
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "18080:18080"
    networks:
      - cabinetpro

  cp-gwt-2:
    build:
      context: CP_GWT
      dockerfile: DockerfileSecond
    container_name: cp-gwt-2
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: second
    ports:
      - "28080:28080"
    networks:
      - cabinetpro

  # ==================
  # Loadbalancer
  # ==================
  loadbalancer:
    build:
      context: nginx
      dockerfile: Dockerfile
    ports:
            - "8080:8080"
    networks:
      - cabinetpro
    depends_on:
      - cp-gwt-1
      - cp-gwt-2

    
networks:
  cabinetpro:
    driver: bridge
