# here we must point to the internal port of application ;)
upstream servers {
    server cp_gwt_1:18080 weight=5 fail_timeout=15s;
    server cp_gwt_2:28080 weight=5 fail_timeout=15s;
}

server {
    # support http and ipv6
    listen 8080 default_server;
    listen [::]:8080 default_server ipv6only=on;

    # path to web
    location /web/ {
        proxy_redirect off;
        proxy_pass http://servers;		
    }

    server_name         www.cabinetpro.ro;

}

